Note title in browser Issue: Title of the note in the browser #2109
streetwriters/notesnook pull request #2127
Opened 2023-03-17 18:07 UTC by Abdulrehman-Jafer

2023-03-18 06:48 UTC, thecodrr requested changes
While this change works for newly opened notes, it doesn't set the document title when the note is saved. The result is that the document title won't be updated when a user changes the note's title.

2023-03-18 06:48 UTC, thecodrr commented on apps/web/src/utils/updateWebTitle.ts
A few issues:

1. There's no license header on this file.
2. Each file in the `utils/` folder can have multiple utilities so instead of naming it `updateWebTitle`, you should name it `document` or `dom` or whatever makes more sense.
3. I recommend installing prettier & eslint extensions in VSCode. If you can't do that, please run them manually on the code you change.

2023-03-18 06:48 UTC, thecodrr commented on apps/web/src/utils/updateWebTitle.ts
> +export const updateWebTitle = (title:string) => {
`updateWebTitle` is ambiguous & might be confusing. Can you change it to `setDocumentTitle`?

2023-03-18 06:48 UTC, thecodrr commented on apps/web/src/utils/updateWebTitle.ts
> +    document.title = `${title}-Notesnook`
```suggestion
    document.title = `${title} - Notesnook`;
```

2023-03-18 09:31 UTC, Abdulrehman-Jafer reviewed
Check it out

2023-03-19 07:23 UTC, thecodrr approved these changes

2023-03-19 07:24 UTC, merged