web: Fix incorrect title on scrolling note
streetwriters/notesnook pull request #4137
Opened 2024-01-17 17:53 UTC by Parthiv-M

2024-01-26 11:22 UTC, thecodrr requested changes

2024-01-26 11:22 UTC, thecodrr commented on apps/web/src/components/editor/toolbar.jsx
> +    document.querySelector("#onScrollTitle").defaultValue = title;
Use a ref instead of `document.querySelector`.

2024-01-26 11:22 UTC, thecodrr commented
@Parthiv-M thanks for fixing this!

2024-01-26 20:18 UTC, Parthiv-M commented
I've made the change

2024-01-27 06:43 UTC, thecodrr commented on apps/web/src/components/editor/toolbar.jsx
> +    onScrollTitleRef.current.defaultValue = title;
```suggestion
    if (onScrollTitleRef.current)
        onScrollTitleRef.current.defaultValue = title;
```

2024-01-27 06:44 UTC, thecodrr approved these changes

2024-01-27 06:44 UTC, merged