Doc app lock
streetwriters/notesnook pull request #6703
Opened 2024-10-15 01:11 UTC by alihamuh

2024-10-15 05:21 UTC, thecodrr requested changes

2024-10-15 05:21 UTC, thecodrr commented on docs/help/contents/app-lock.md
> +> App lock is not available on Web.
App lock is available on web & desktop.

2024-10-15 05:21 UTC, thecodrr commented on docs/help/contents/app-lock.md
> +<img src="/desktop-password-key.png" alt="drawing" height="500"/>
We should split these into their own headings so its easier to refer a specific App Lock feature to a user. That way we'll also be able to add more information to each topic easily.

2024-10-16 06:07 UTC, merged

2024-10-16 06:40 UTC, alihamuh commented
new commit made 2.0